### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dcabib** [rooneyrulz/event_book#1]
There is no documentation at all for building and running the application. It's not possible to start the server or client by "default".... There are some package errors....

**Comment by dcabib** [comment]
abib$ cd client 
abib$ npm install

> fsevents@1.2.6 install /private/tmp/event_book/client/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/private/tmp/event_book/client/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote

> node-sass@4.10.0 install /private/tmp/event_book/client/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/abib/.npm/node-sass/4.10.0/darwin-x64-67_binding.node

> node-sass@4.10.0 postinstall /private/tmp/event_book/client/node_modules/node-sass
> node scripts/build.js

Binary found at /private/tmp/event_book/client/node_modules/node-sass/vendor/darwin-x64-67/binding.node
Testing binary
Binary is fine
added 1146 packages from 1193 contributors and audited 40185 packages in 61.179s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details



abib:client abib$ ng serve
Your global Angular CLI version (7.3.0) is greater than your local
version (7.1.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 91% additional asset processing scripts-webpack-plugin✖ ｢wdm｣: Error: ENOENT: no such file or directory, open '/private/tmp/event_book/client/bower_components/jquery/dist/jquery.min.js'
    at Object.openSync (fs.js:450:3)
    at Object.readFileSync (fs.js:350:35)
    at Storage.provideSync (/private/tmp/event_book/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (/private/tmp/event_book/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/private/tmp/event_book/client/node_modules/@ngtools/webpack/src/webpack-input-host.js:35:51)
    at Observable._trySubscribe (/private/tmp/event_book/client/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/private/tmp/event_book/client/node_modules/rxjs/internal/Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (/private/tmp/event_book/client/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.read (/private/tmp/event_book/client/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (/private/tmp/event_book/client/node_modules/@ngtools/webpack/src/compiler_host.js:124:44)
    at VirtualFileSystemDecorator.readFile (/private/tmp/event_book/client/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:39:54)
    at Promise (/private/tmp/event_book/client/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:92:49)
    at new Promise (<anonymous>)
    at scripts.map.fullPath (/private/tmp/event_book/client/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:91:24)
    at Array.map (<anonymous>)
    at hook (/private/tmp/event_book/client/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:90:43)
^C
